import {Engine} from '@babylonjs/core/Engines/engine';
import {Scene} from '@babylonjs/core/scene';
import {ArcRotateCamera} from '@babylonjs/core/Cameras/arcRotateCamera';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder';
import {TransformNode} from '@babylonjs/core/Meshes/transformNode';
import {Vector3} from '@babylonjs/core/Maths/math.vector';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color';
import '@babylonjs/core/Meshes/Builders/boxBuilder';import '@babylonjs/core/Meshes/Builders/sphereBuilder';import '@babylonjs/core/Meshes/Builders/groundBuilder';import '@babylonjs/core/Meshes/Builders/cylinderBuilder';
const $=s=>document.querySelector(s),canvas=$('#game'),start=$('#start'),prey=$('#prey'),health=$('#health'),stam=$('#stamina'),status=$('#status'),bannerEl=$('#banner'),stick=$('#stick'),nub=stick.querySelector('i');
const engine=new Engine(canvas,true),scene=new Scene(engine);scene.clearColor=new Color4(.52,.86,1,1);
const camera=new ArcRotateCamera('camera',-Math.PI/2,1.03,16,new Vector3(0,1,0),scene);camera.inputs.clear();camera.lowerRadiusLimit=16;camera.upperRadiusLimit=16;
new HemisphericLight('sky',new Vector3(0,1,0),scene).intensity=.9;new DirectionalLight('sun',new Vector3(-.4,-1,-.3),scene).intensity=.8;
const arena=27,targetPrey=5,keys=new Set(),touch={dash:false,attack:false,special:false,vision:false,stalk:false},controlCodes=new Set(['KeyW','KeyA','KeyS','KeyD','KeyH','KeyI','KeyJ','KeyK','KeyL','KeyP','Space','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','AltLeft','AltRight']),R=(a,b)=>a+Math.random()*(b-a),C=(v,a,b)=>Math.max(a,Math.min(b,v)),D=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),TAU=Math.PI*2;
function mat(n,c,e=0){const m=new StandardMaterial(n,scene);m.diffuseColor=c;if(e)m.emissiveColor=c.scale(e);return m}
const M={grass:mat('grass',new Color3(.16,.62,.16)),dark:mat('deep grass',new Color3(.05,.28,.1)),court:mat('court',new Color3(.18,.45,.75)),soil:mat('soil',new Color3(.34,.2,.1)),stone:mat('stone',new Color3(.5,.48,.43)),snake:mat('neon snake',new Color3(.48,1,.08),.25),belly:mat('belly',new Color3(.95,1,.58),.08),mouse:mat('mouse',new Color3(.68,.62,.55)),pink:mat('pink nose',new Color3(1,.13,.74),1),dog:mat('bluey',new Color3(.15,.34,.95)),gardener:mat('gardener',new Color3(.95,.9,.25)),mower:mat('mower',new Color3(.9,.1,.08)),scent:mat('scent',new Color3(1,.2,.85),1)};
function box(n,p,s,m){const x=MeshBuilder.CreateBox(n,{size:1},scene);x.position=p;x.scaling=s;x.material=m;return x}function sphere(n,p,d,m){const x=MeshBuilder.CreateSphere(n,{diameter:d,segments:14},scene);x.position=p;x.material=m;return x}
MeshBuilder.CreateGround('lawn',{width:arena*2,height:arena*2},scene).material=M.grass;box('sport court',new Vector3(13,.03,9),new Vector3(11,.05,8),M.court);box('garden bed',new Vector3(-13,.1,-9),new Vector3(8,.2,7),M.soil);for(let i=0;i<70;i++){let b=box('grass blade',new Vector3(R(-arena,arena),.45,R(-arena,arena)),new Vector3(.08,R(.7,1.7),.08),M.dark);b.rotation.z=R(-.35,.35)}for(let i=0;i<12;i++){let a=i/12*Math.PI*2,s=MeshBuilder.CreateCylinder('fire pit stone',{diameter:1.2,height:.45,tessellation:10},scene);s.position=new Vector3(Math.cos(a)*3.6-4,.22,Math.sin(a)*3.6+10);s.material=M.stone}box('north fence',new Vector3(0,1.3,-arena-.6),new Vector3(arena*2,2.6,.45),M.stone);box('south fence',new Vector3(0,1.3,arena+.6),new Vector3(arena*2,2.6,.45),M.stone);box('west fence',new Vector3(-arena-.6,1.3,0),new Vector3(.45,2.6,arena*2),M.stone);box('east fence',new Vector3(arena+.6,1.3,0),new Vector3(.45,2.6,arena*2),M.stone);
const snake=new TransformNode('baby snake',scene),head=sphere('head',new Vector3(0,.62,0),1.05,M.snake);head.parent=snake;sphere('eye',new Vector3(-.22,.9,.42),.13,mat('eye',new Color3(0,0,0))).parent=snake;sphere('eye',new Vector3(.22,.9,.42),.13,mat('eye2',new Color3(0,0,0))).parent=snake;const seg=[];for(let i=0;i<10;i++){let s=sphere('body',new Vector3(0,.42,-.55-i*.42),.88-i*.035,i%2?M.snake:M.belly);s.parent=snake;seg.push(s)}const trail=Array.from({length:90},()=>snake.position.clone());
function mouse(i){const r=new TransformNode('mouse'+i,scene);r.position=new Vector3(R(-21,21),.35,R(-21,21));let b=sphere('mouse body',Vector3.Zero(),.95,M.mouse);b.scaling.z=1.35;b.parent=r;let n=sphere('glowing nose',new Vector3(0,.05,.68),.32,M.pink);n.parent=r;let scent=Array.from({length:7},()=>{let s=sphere('scent',Vector3.Zero(),.16,M.scent);s.isVisible=false;return s});return{r,n,scent,dir:{x:R(-1,1),z:R(-1,1)},eaten:false,scared:0}}const mice=Array.from({length:targetPrey},(_,i)=>mouse(i));
function threat(kind,p){let m=box(kind,p,kind==='dog'?new Vector3(1.8,1,2.3):kind==='gardener'?new Vector3(1,1.9,1):new Vector3(2.1,.8,1.4),M[kind]);return{kind,m,dir:{x:R(-1,1),z:R(-1,1)},timer:R(1,3)}}const threats=[threat('dog',new Vector3(14,.8,-12)),threat('gardener',new Vector3(-18,1,15)),threat('gardener',new Vector3(19,1,17)),threat('mower',new Vector3(-20,.45,-2))];
const P={started:false,prey:0,health:3,stamina:1,angle:0,flop:0,vision:0,inv:0,done:false};let joy={x:0,z:0},lastA=false,lastY=false,lastV=false,audio=null;
function tone(f,d=.08){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d)}function banner(t,ms=1500){bannerEl.textContent=t;bannerEl.hidden=false;setTimeout(()=>bannerEl.hidden=true,ms)}
function input(){let gp=[...navigator.getGamepads?.()||[]].find(Boolean),turn=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0)+joy.x,forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joy.z,d=keys.has('KeyK')||keys.has('ShiftLeft')||keys.has('ShiftRight')||touch.dash,st=keys.has('KeyH')||keys.has('AltLeft')||keys.has('AltRight')||touch.stalk,a=keys.has('KeyJ')||keys.has('Space')||touch.attack,y=keys.has('KeyL')||touch.special,v=keys.has('KeyI')||keys.has('KeyP')||touch.vision;if(gp){turn+=(Math.abs(gp.axes[0])>.15?gp.axes[0]:0);forward+=-(Math.abs(gp.axes[1])>.15?gp.axes[1]:0);d||=(gp.buttons[7]?.value??0)>.55;st||=(gp.buttons[6]?.value??0)>.35;a||=gp.buttons[2]?.pressed;y||=gp.buttons[3]?.pressed;v||=gp.buttons[12]?.pressed}return{turn:C(turn,-1,1),forward:C(forward,-1,1),dash:d,stalk:st,attack:a,special:y,vision:v}}
function lerpAngle(a,b,t){let d=((b-a+Math.PI)%TAU+TAU)%TAU-Math.PI;return a+d*t}function followCamera(dt){camera.beta=1.03;camera.radius=16;camera.alpha=lerpAngle(camera.alpha,-P.angle-Math.PI/2,Math.min(1,dt*8));camera.target=Vector3.Lerp(camera.target,snake.position.add(new Vector3(0,.9,0)),Math.min(1,dt*8))}
function reset(){snake.position.set(0,0,0);Object.assign(P,{prey:0,health:3,stamina:1,flop:0,done:false});mice.forEach(m=>{m.eaten=false;m.r.setEnabled(true);m.r.position=new Vector3(R(-21,21),.35,R(-21,21))});banner('Back in the grass. Hunt again.')}function damage(t){if(P.inv||P.done)return;P.health--;P.inv=1.2;banner(t);tone(120,.16);if(P.health<=0)reset()}
function eat(){let best=null,bd=99;for(const m of mice){if(m.eaten)continue;let d=D(snake.position,m.r.position);if(d<bd){bd=d;best=m}}if(best&&bd<2.85){best.eaten=true;best.r.setEnabled(false);best.scent.forEach(s=>s.dispose());P.prey++;tone(660);banner(`Mouse caught! ${P.prey}/${targetPrey}`,900);if(P.prey>=targetPrey){P.done=true;M.snake.emissiveColor=new Color3(.65,1,.15).scale(.7);banner('EVOLUTION READY: Stage 2 Rattlesnake unlocked!',3600);tone(880,.22)}}else tone(180,.05)}
function update(dt,I){if(I.special&&!lastY&&P.flop<=0){P.flop=3;banner('Dramatic Flop!');tone(260,.13)}if(I.vision&&!lastV){P.vision=4;banner('Predator Vision: scent trails glowing.');tone(760,.12)}if(I.attack&&!lastA&&P.flop<=0)eat();lastA=I.attack;lastY=I.special;lastV=I.vision;P.vision=Math.max(0,P.vision-dt);P.inv=Math.max(0,P.inv-dt);
if(P.flop>0){P.flop-=dt;snake.rotation.x=1.4+Math.sin(performance.now()*.012)*.18}else{snake.rotation.x=0;let moving=Math.abs(I.forward)>.05,dashing=I.dash&&P.stamina>.05,speed=(I.stalk?3:dashing?9.2:5)*(I.forward<0?.62:1);if(Math.abs(I.turn)>.04)P.angle+=I.turn*dt*3.2;if(dashing&&moving)P.stamina=C(P.stamina-dt*.42,0,1);else P.stamina=C(P.stamina+dt*.24,0,1);if(moving){let fx=Math.sin(P.angle),fz=Math.cos(P.angle);snake.position.x=C(snake.position.x+fx*speed*I.forward*dt,-arena+1,arena-1);snake.position.z=C(snake.position.z+fz*speed*I.forward*dt,-arena+1,arena-1)}snake.rotation.y=P.angle;trail.unshift(snake.position.clone());trail.length=90;seg.forEach((s,i)=>{let p=trail[Math.min(trail.length-1,5+i*4)];s.position.x=p.x-snake.position.x;s.position.z=p.z-snake.position.z;s.position.y=.4+Math.sin(performance.now()*.006+i)*.04})}
for(const m of mice){if(m.eaten)continue;let away=m.r.position.subtract(snake.position),close=away.length()<4.2;if(close){let n=away.normalize();m.dir={x:n.x,z:n.z};m.scared=.45}else if(Math.random()<dt*.55)m.dir={x:R(-1,1),z:R(-1,1)};let len=Math.hypot(m.dir.x,m.dir.z)||1,sp=m.scared>0?3.2:1.35;m.r.position.x=C(m.r.position.x+m.dir.x/len*sp*dt,-arena+1,arena-1);m.r.position.z=C(m.r.position.z+m.dir.z/len*sp*dt,-arena+1,arena-1);m.r.rotation.y=Math.atan2(m.dir.x,m.dir.z);m.scared=Math.max(0,m.scared-dt);m.n.scaling.setAll(1+Math.sin(performance.now()*.01)*.22);m.scent.forEach((s,i)=>{let t=(i+1)/(m.scent.length+1);s.isVisible=P.vision>0;s.position=Vector3.Lerp(snake.position,m.r.position,t).add(new Vector3(0,.45+Math.sin(t*12+performance.now()*.004)*.3,0))})}
let camo=D(snake.position,new Vector3(-4,0,10))<4.5?.45:1,hide=I.stalk?.45:1;for(const t of threats){t.timer-=dt;let d=D(t.m.position,snake.position);if(t.kind==='mower'){t.m.position.x+=4.6*dt;if(t.m.position.x>arena)t.m.position.x=-arena;if(d<1.8)damage('Clipped by the lawnmower!');continue}let detect=(t.kind==='dog'?10.5:8)*camo*hide;if(d<detect&&P.flop<=0){let c=snake.position.subtract(t.m.position).normalize();t.dir={x:c.x,z:c.z}}else if(t.timer<0){t.dir={x:R(-1,1),z:R(-1,1)};t.timer=R(1.2,3.6)}if(P.flop>0&&d<4&&t.kind==='gardener'){snake.position.x=R(-20,20);snake.position.z=R(-20,20);P.flop=0;banner('The gardener flicked you across the yard!');tone(520,.12)}let len=Math.hypot(t.dir.x,t.dir.z)||1,sp=t.kind==='dog'?4.4:3.25;t.m.position.x=C(t.m.position.x+t.dir.x/len*sp*dt,-arena+1,arena-1);t.m.position.z=C(t.m.position.z+t.dir.z/len*sp*dt,-arena+1,arena-1);t.m.rotation.y=Math.atan2(t.dir.x,t.dir.z);if(d<(t.kind==='dog'?2.2:1.7)){if(P.flop>0&&t.kind==='dog')banner('Bluey sniffed your flop and walked away.');else damage(t.kind==='dog'?'Bluey pounced too close!':'The gardener spotted you!')}}
prey.textContent=`${P.prey} / ${targetPrey}`;health.textContent=`${P.health} / 3`;stam.style.width=`${Math.round(P.stamina*100)}%`;status.textContent=P.done?'Evolving':P.flop>0?'Playing Dead':I.stalk?'Stalking':threats.some(t=>D(t.m.position,snake.position)<7)?'Danger':'Hidden';followCamera(dt);if(P.done)snake.scaling.setAll(1+Math.sin(performance.now()*.006)*.12)}
window.addEventListener('keydown',e=>{if(controlCodes.has(e.code))e.preventDefault();keys.add(e.code)});window.addEventListener('keyup',e=>{if(controlCodes.has(e.code))e.preventDefault();keys.delete(e.code)});let sp=-1;stick.addEventListener('pointerdown',e=>{sp=e.pointerId;stick.setPointerCapture(sp)});stick.addEventListener('pointermove',e=>{if(e.pointerId!==sp)return;let r=stick.getBoundingClientRect(),x=C((e.clientX-r.left-r.width/2)/46,-1,1),z=C((e.clientY-r.top-r.height/2)/46,-1,1);joy={x,z};nub.style.transform=`translate(${x*34}px,${z*34}px)`});stick.addEventListener('pointerup',()=>{joy={x:0,z:0};nub.style.transform='';sp=-1});document.querySelectorAll('[data-act]').forEach(b=>{let a=b.dataset.act;b.addEventListener('pointerdown',e=>{e.preventDefault();touch[a]=true});b.addEventListener('pointerup',()=>touch[a]=false);b.addEventListener('pointerleave',()=>touch[a]=false)});$('#startBtn').addEventListener('click',()=>{start.style.display='none';P.started=true;try{audio?.resume()}catch{}tone(440,.1);banner('Catch 5 slower mice to evolve.')});
engine.runRenderLoop(()=>{if(P.started)update(Math.min(engine.getDeltaTime()/1000,.04),input());scene.render()});window.addEventListener('resize',()=>engine.resize());
